CREATE DATABASE customer_behavior;
USE customer_behavior;

-- total revenue generated by male vs. female customers
SELECT 
    gender, 
    SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- customers used a discount but still spent more than the average purchase amount
SELECT 
    customer_id, 
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes' 
AND purchase_amount >= (
    SELECT AVG(purchase_amount) 
    FROM customer
);

-- top 5 products with the highest average review rating
SELECT 
    item_purchased, 
    ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))), 2) AS average_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_product_rating DESC
LIMIT 5;

-- average Purchase Amounts between Standard and Express Shipping
SELECT 
    shipping_type, 
    ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5. average spend and total revenue between subscribers and non-subscribers
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- 5 products have the highest percentage of purchases with discounts applied
SELECT 
    item_purchased,
    ROUND(
        100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
        / COUNT(*), 
    2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment 
WITH customer_type AS (
    SELECT 
        customer_id, 
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT 
    customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

-- top 3 most purchased products within each category
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    item_rank,
    category, 
    item_purchased, 
    total_orders
FROM item_counts
WHERE item_rank <= 3;

-- customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- revenue contribution of each age group
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

-- adding financial kpi layer
-- Customer-Level Revenue Table
CREATE VIEW customer_summary AS
SELECT 
    customer_id,
    SUM(purchase_amount) AS total_revenue,
    COUNT(*) AS total_orders,
    AVG(purchase_amount) AS avg_order_value,
    MAX(previous_purchases) AS previous_purchases,
    subscription_status,
    age_group
FROM customer
GROUP BY customer_id, subscription_status, age_group;


-- Customer Lifetime Value (CLV)
-- CLV = Avg Order Value × Total Orders
SELECT 
    customer_id,
    ROUND(avg_order_value * total_orders, 2) AS customer_lifetime_value
FROM customer_summary;

-- Repeat Purchase Rate
SELECT 
    ROUND(
        100 * SUM(CASE WHEN previous_purchases > 1 THEN 1 ELSE 0 END) 
        / COUNT(*),
    2) AS repeat_purchase_rate
FROM customer_summary;

-- Incentive / Commission Simulation
-- commission logic
SELECT 
    customer_id,
    total_revenue,
    CASE 
        WHEN total_revenue < 5000 THEN total_revenue * 0.02
        WHEN total_revenue BETWEEN 5000 AND 20000 THEN total_revenue * 0.05
        ELSE total_revenue * 0.08
    END AS simulated_commission
FROM customer_summary;

-- subscription bonus rule
SELECT 
    customer_id,
    total_revenue,
    subscription_status,
    CASE 
        WHEN subscription_status = 'Yes' THEN 1000
        ELSE 0
    END AS subscription_bonus
FROM customer_summary;


